### ISSUE TITLE
Light curve error snake on IPython notebook sliders page for x0 distribution

### ISSUE THREAD

**Issue by bhayden53** [scplbl/lilys.class.src#1]
Currently the IPython notebook for light curves picks some x0 near the center of the distribution. However, we do need to see 1+ sigma fluctuations of the x0 value. This could take the form of 2 dotted or dashed lightcurves, one at + n-sigma x0, and one at -n-sigma x0. 

This will then make it easier to compare the light curve plot from the notebook to the value of the survival function, because the x0 is a crucial piece of the survival function that can't be replicated on the notebook currently.

**Comment by sofiatti** [comment]
This no longer belongs here. Should be in light curve.
