### ISSUE TITLE
makePlots does not using existing 'file_with_RF_and_SF_arrays'

### ISSUE THREAD

**Issue by bhayden53** [scplbl/lilys.class.src#6]
When this file already exists, makePlots clobbers it anyway and starts over. makePlots take 20-30 minutes to run so this can be quite an issue.

**Comment by sofiatti** [comment]
Hi Brian, this is not a bug. For the output file, the code uses the outdir as a prefix. When you enter a file, it expects the full directory name. Would you like me to have it not use the outdir as a prefix for generating the file?

**Comment by bhayden53** [comment]
What I'm suggesting is that when it goes to make this file, it should always check if the file already exists in that location. i.e. with os.path.isfile. If the file is already there, then it doesn't run the part that takes a really long time. 
for example:

```
if os.path.isfile(outdir+file_with_RF_and_SF_arrays):
    dont_do_the_thing_that_takes_30_minutes
else:
    do_the_thing_that_takes_30_minutes
```

Currently, it's starting over even if outdir+file_with_RF_and_SF_arrays is already there.

**Comment by sofiatti** [comment]
Right. Because it checks if file_with_RF_and_SF is there. And it won't be unless you renamed it. I.e., it's not checking for outdir+file_with_RF_and_SF_arrays. It's confusing and silly. I'm changing it now so that it checks it in the outdir.

**Comment by bhayden53** [comment]
Yes, I think changing it to check in outdir is the right solution.

**Comment by sofiatti** [comment]
All done! Should be working the way you expect now. 

P.S.: Gitignore is not ignoring my input.yaml file, despite my requests. Keep the name 'input.yaml' just as an example yaml file (i.e., name the important yaml files as something else)

**Comment by sofiatti** [comment]
I'll just rename input.yaml as example.yaml.
